# This is used from within the target folder when building using GitHub.

site_draft:
  id: ehf-preaward-g2-draft
  type: site
  path: site
  properties:
    domain: anskaffelser.dev
    path: preaward/g2/spec/draft

site_current:
  mode: release
  id: ehf-preaward-g2-current
  type: site
  path: site
  properties:
    domain: anskaffelser.dev
    path: preaward/g2/spec/current