name: Build

on:
  push:
    branches:
      - master
    tags:
        - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: anskaffelser/ehftools:edge

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Copy deployment configuration
        run: cp .deploy.yml target/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target

  deploy-draft:
    name: Deploy [Draft]
    runs-on: ubuntu-latest
    needs: build
    if: "!startsWith(github.ref, 'refs/tags/')"

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Deploy
        env:
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: docker run --rm -i -e DEPLOY_SERVICE -e DEPLOY_TOKEN -v $(pwd):/src -w /src klakegg/deployer:edge push

  deploy-current:
    name: Deploy [Current]
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Upload validation artifact
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "validator/no.anskaffelser.ehf.preaward.g2-${TAG}.asice"
          label: "Validation artifacts for VEFA Validator 2.x"
          type: "application/vnd.difi.validator.v2+zip"

      - name: Upload examples files
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "examples.zip"
          name: "ehf-preaward-g2-examples-${TAG}.zip"
          label: "Example files"

      - name: Upload Schematron files
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "schematron.zip"
          name: "ehf-preaward-g2-schematron-${TAG}.zip"
          label: "Schematron files"

      - name: Package site files
        run: cd site && zip -rq ../site.zip *

      - name: Upload site files
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "site.zip"
          name: "ehf-preaward-g2-site-${TAG}.zip"
          label: "Site files"

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: docker run --rm -i -e DEPLOY_SERVICE -e DEPLOY_TOKEN -v $(pwd):/src -w /src klakegg/deployer:edge push -m release
